import { testMock } from '../config'

testMock('address',
  [
    '@ip',
    '@ip()',
    '@ip6()',
    '@url()',
    '@domain',
    '@domain()',
    '@email()',
    '@region',
    '@province',
    '@city',
    '@district',
    '@address',
    '@address(RR PP CC DD)',
    '@region',
    '@province',
    '@city',
    // '@district',
    '@address',
    '@address(RR PP CC DD)',
    '@region',
    '@province',
    '@city',
    // '@district',
    '@address',
    '@address(RR PP CC DD)',
    '@region',
    '@province',
    '@city',
    '@district',
    '@address',
    '@address(RR PP CC DD)',
  ]
)