import { mock } from '../../src'
import { test } from 'unit-testing-js'
import { isNoEmpty } from 'asura-eye'

test('test-item', isNoEmpty,
	{ tobe: true, param: mock('@num(1.1,2.3)'), },
	{ tobe: true, param: mock('@num(1.1,2.3)'), },
	{ tobe: true, param: mock({ 'num|1-9': 1 }), },
	{ tobe: true, param: mock({ 'num|12': 1 }), },
	{ tobe: true, param: mock({ "value|2-4": { name: "@name" } }), },
	{ tobe: true, param: mock('@name'), },
	{ tobe: true, param: mock('@cname'), },
	{ tobe: true, param: mock('@first'), },
	{ tobe: true, param: mock('@last'), },
	{ tobe: true, param: mock('@cfirst'), },
	{ tobe: true, param: mock('@clast'), },
	{ tobe: true, param: mock('@name'), },
	{ tobe: true, param: mock('@char'), },
	{ tobe: true, param: mock('@string'), },
	{ tobe: true, param: mock('@title'), },
	{ tobe: true, param: mock('@title(1,30)'), },
	{ tobe: true, param: mock('@id'), },
	{ tobe: true, param: mock('@uuid'), },
	{ tobe: true, param: mock('@boolean'), },
	{ tobe: true, param: mock('@cword'), },
	{ tobe: true, param: mock('@uuid(xxyxxxyyy)'), },
	{ tobe: true, param: mock('@string(3,4)'), },
	{ tobe: true, param: mock('@uuid(xxx)'), },
	{ tobe: true, param: mock({ t: '@title(3,4)' }), },
	{ tobe: true, param: mock('@image(晓峰也牛逼,400x400,30)'), },
	{ tobe: true, param: mock('@image(文字,200x200,123,456,png)'), },
	{ tobe: true, param: mock({ "name&&a": "@name" }), },
	{ tobe: true, param: mock({ 'name|3': '@name' }), },
	{ tobe: true, param: mock({ 'name|3-5': '@name' }), },
	{ tobe: true, param: mock('@char'), },
	{ tobe: true, param: mock('@name'), },
	{ tobe: true, param: mock('@cname'), },
	{ tobe: true, param: mock('@string'), },
	{ tobe: true, param: mock('@title'), },
	{ tobe: true, param: mock('@title(1,30)') },
)