// import './address'
// import './time'
// import './num'
// import './sentence'
// import './paragraph'
// import './test'
// import './test2'
// import './base'
// import './RandomList'
// import './reg'
// import './newRuleTest'
// import './md'

// import './count.1.test'
// import './count.number.test'
import './cases/min.max.test'